# Generated by Django 4.0.6 on 2022-07-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.TextField(max_length=255)),
                ('Country', models.TextField(max_length=255)),
                ('Item_type', models.TextField(max_length=255)),
                ('Sales_channel', models.TextField(max_length=255)),
                ('Order_priority', models.TextField(max_length=255)),
                ('Order_date', models.DateField()),
                ('Order_id', models.IntegerField()),
                ('Ship_date', models.DateField()),
                ('Units_sold', models.IntegerField()),
                ('Unit_price', models.IntegerField()),
                ('Unit_cost', models.IntegerField()),
                ('Total_revenue', models.IntegerField()),
                ('Total_cost', models.IntegerField()),
                ('Total_profit', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Sales journal entries',
            },
        ),
    ]
