# Generated by Django 4.0.6 on 2022-07-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='Total_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Total_profit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Total_revenue',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Unit_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Unit_price',
            field=models.FloatField(),
        ),
    ]
